INPUT_NO = 0 #will be modified
OUTPUT_NO = 0 #will be modified
TESTS_NO = 0 #will bie modified
EXAM_NO = 0 #will be modified
INPUT_MIN = [] #will be modified
INPUT_MAX = [] #will be modified
OUTPUT_MIN = [] #will be modified
OUTPUT_MAX = [] #will be modified
MAX_HIDLAYERS = 4 #no of hidden layers maximum
MULTIP_LIST = [0.5, 1, 2, 4, 8] # input_no will randomly be * with this number pool in order to create the neural networks hidden layers, default [0.5, 1, 2, 4, 8] !THE GROWING ORDER IS A MUST!
TEMPLATE_NO = 32 #n.o. templates, minimum 4, default 32
EPOCHS = [10, 30, 50, 100] #nmb of eras for every competition stage, default [10, 30, 50, 100]
W_INIT = [1.0, 1.0] #range of init of weight and bias mat, default [-1.0, 1.0]
LEARNING_RATE = 0.01 #learning rate :)), default 0.01
QUALIFY = [16, 8, 4, 2] #how many templates should remain after each round, last one MUST remain 2, default [16, 8, 4, 2]
COMP_LENGHT = 4 #how many rounds should be in competition